# Generated by Django 4.1.5 on 2023-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=36)),
                ("first_name", models.CharField(max_length=36)),
                ("last_name", models.CharField(max_length=36)),
                ("email", models.CharField(max_length=36)),
                ("password", models.CharField(max_length=16)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
