# Generated by Django 4.1.5 on 2023-01-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_musicpost_song_like_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="musicpost",
            name="user",
        ),
        migrations.AddField(
            model_name="musicpost",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="musicpost",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music_posts",
                to="app.user",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="music_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="app.musicpost",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="app.user",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="music_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="app.musicpost",
            ),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
